// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;
VL_MODULE(Vtop___024root) {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_offsets_0,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_offsets_1,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_0_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_offsets_0,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_offsets_1,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_1_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_offsets_0,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_offsets_1,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_is_jalr,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_is_call,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_is_ret,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_last_may_be_rvi_call,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_2_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_offsets_0,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_offsets_1,3,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_fallThroughErr,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s2_full_pred_3_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_fallThroughErr,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_multiHit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_0_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_fallThroughErr,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_multiHit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_1_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_fallThroughErr,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_multiHit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_is_jalr,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_is_call,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_is_ret,0,0);
    };
    struct {
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_2_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_slot_valids_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_slot_valids_1,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_offsets_0,3,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_offsets_1,3,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_fallThroughErr,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_multiHit,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_is_br_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_s3_full_pred_3_hit,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_isCall,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_isRet,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_isJalr,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_valid,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_offset,3,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_valid,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_tarStat,1,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_offset,3,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_sharing,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_valid,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_tarStat,1,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_pftAddr,3,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_carry,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_last_may_be_rvi_call,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_always_taken_0,0,0);
        VL_IN8(io_in_bits_resp_in_0_last_stage_ftb_entry_always_taken_1,0,0);
        VL_OUT8(io_out_s2_full_pred_0_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s2_full_pred_0_br_taken_mask_1,0,0);
        VL_OUT8(io_out_s2_full_pred_0_slot_valids_0,0,0);
        VL_OUT8(io_out_s2_full_pred_0_slot_valids_1,0,0);
        VL_OUT8(io_out_s2_full_pred_0_offsets_0,3,0);
        VL_OUT8(io_out_s2_full_pred_0_offsets_1,3,0);
        VL_OUT8(io_out_s2_full_pred_0_is_br_sharing,0,0);
        VL_OUT8(io_out_s2_full_pred_0_hit,0,0);
        VL_OUT8(io_out_s2_full_pred_1_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s2_full_pred_1_br_taken_mask_1,0,0);
        VL_OUT8(io_out_s2_full_pred_1_slot_valids_0,0,0);
        VL_OUT8(io_out_s2_full_pred_1_slot_valids_1,0,0);
        VL_OUT8(io_out_s2_full_pred_1_offsets_0,3,0);
        VL_OUT8(io_out_s2_full_pred_1_offsets_1,3,0);
        VL_OUT8(io_out_s2_full_pred_1_is_br_sharing,0,0);
        VL_OUT8(io_out_s2_full_pred_1_hit,0,0);
        VL_OUT8(io_out_s2_full_pred_2_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s2_full_pred_2_br_taken_mask_1,0,0);
        VL_OUT8(io_out_s2_full_pred_2_slot_valids_0,0,0);
        VL_OUT8(io_out_s2_full_pred_2_slot_valids_1,0,0);
        VL_OUT8(io_out_s2_full_pred_2_offsets_0,3,0);
        VL_OUT8(io_out_s2_full_pred_2_offsets_1,3,0);
        VL_OUT8(io_out_s2_full_pred_2_is_br_sharing,0,0);
        VL_OUT8(io_out_s2_full_pred_2_hit,0,0);
        VL_OUT8(io_out_s2_full_pred_3_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s2_full_pred_3_br_taken_mask_1,0,0);
        VL_OUT8(io_out_s2_full_pred_3_slot_valids_0,0,0);
        VL_OUT8(io_out_s2_full_pred_3_slot_valids_1,0,0);
        VL_OUT8(io_out_s2_full_pred_3_offsets_0,3,0);
        VL_OUT8(io_out_s2_full_pred_3_offsets_1,3,0);
        VL_OUT8(io_out_s2_full_pred_3_fallThroughErr,0,0);
        VL_OUT8(io_out_s2_full_pred_3_is_br_sharing,0,0);
        VL_OUT8(io_out_s2_full_pred_3_hit,0,0);
        VL_OUT8(io_out_s3_full_pred_0_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s3_full_pred_0_br_taken_mask_1,0,0);
    };
    struct {
        VL_OUT8(io_out_s3_full_pred_0_slot_valids_0,0,0);
        VL_OUT8(io_out_s3_full_pred_0_slot_valids_1,0,0);
        VL_OUT8(io_out_s3_full_pred_0_fallThroughErr,0,0);
        VL_OUT8(io_out_s3_full_pred_0_multiHit,0,0);
        VL_OUT8(io_out_s3_full_pred_0_is_br_sharing,0,0);
        VL_OUT8(io_out_s3_full_pred_0_hit,0,0);
        VL_OUT8(io_out_s3_full_pred_1_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s3_full_pred_1_br_taken_mask_1,0,0);
        VL_OUT8(io_out_s3_full_pred_1_slot_valids_0,0,0);
        VL_OUT8(io_out_s3_full_pred_1_slot_valids_1,0,0);
        VL_OUT8(io_out_s3_full_pred_1_fallThroughErr,0,0);
        VL_OUT8(io_out_s3_full_pred_1_multiHit,0,0);
        VL_OUT8(io_out_s3_full_pred_1_is_br_sharing,0,0);
        VL_OUT8(io_out_s3_full_pred_1_hit,0,0);
        VL_OUT8(io_out_s3_full_pred_2_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s3_full_pred_2_br_taken_mask_1,0,0);
        VL_OUT8(io_out_s3_full_pred_2_slot_valids_0,0,0);
        VL_OUT8(io_out_s3_full_pred_2_slot_valids_1,0,0);
        VL_OUT8(io_out_s3_full_pred_2_fallThroughErr,0,0);
        VL_OUT8(io_out_s3_full_pred_2_multiHit,0,0);
        VL_OUT8(io_out_s3_full_pred_2_is_br_sharing,0,0);
        VL_OUT8(io_out_s3_full_pred_2_hit,0,0);
        VL_OUT8(io_out_s3_full_pred_3_br_taken_mask_0,0,0);
        VL_OUT8(io_out_s3_full_pred_3_br_taken_mask_1,0,0);
        VL_OUT8(io_out_s3_full_pred_3_slot_valids_0,0,0);
        VL_OUT8(io_out_s3_full_pred_3_slot_valids_1,0,0);
        VL_OUT8(io_out_s3_full_pred_3_offsets_0,3,0);
        VL_OUT8(io_out_s3_full_pred_3_offsets_1,3,0);
        VL_OUT8(io_out_s3_full_pred_3_fallThroughErr,0,0);
        VL_OUT8(io_out_s3_full_pred_3_multiHit,0,0);
        VL_OUT8(io_out_s3_full_pred_3_is_br_sharing,0,0);
        VL_OUT8(io_out_s3_full_pred_3_hit,0,0);
        VL_OUT8(io_out_last_stage_spec_info_ssp,3,0);
        VL_OUT8(io_out_last_stage_spec_info_sctr,2,0);
        VL_OUT8(io_out_last_stage_spec_info_TOSW_flag,0,0);
        VL_OUT8(io_out_last_stage_spec_info_TOSW_value,4,0);
        VL_OUT8(io_out_last_stage_spec_info_TOSR_flag,0,0);
        VL_OUT8(io_out_last_stage_spec_info_TOSR_value,4,0);
        VL_OUT8(io_out_last_stage_spec_info_NOS_flag,0,0);
        VL_OUT8(io_out_last_stage_spec_info_NOS_value,4,0);
        VL_OUT8(io_out_last_stage_ftb_entry_isCall,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_isRet,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_isJalr,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_valid,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_brSlots_0_offset,3,0);
        VL_OUT8(io_out_last_stage_ftb_entry_brSlots_0_sharing,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_brSlots_0_valid,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_brSlots_0_tarStat,1,0);
        VL_OUT8(io_out_last_stage_ftb_entry_tailSlot_offset,3,0);
        VL_OUT8(io_out_last_stage_ftb_entry_tailSlot_sharing,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_tailSlot_valid,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_tailSlot_tarStat,1,0);
        VL_OUT8(io_out_last_stage_ftb_entry_pftAddr,3,0);
        VL_OUT8(io_out_last_stage_ftb_entry_carry,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_last_may_be_rvi_call,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_always_taken_0,0,0);
        VL_OUT8(io_out_last_stage_ftb_entry_always_taken_1,0,0);
        VL_IN8(io_ctrl_ras_enable,0,0);
        VL_IN8(io_s0_fire_0,0,0);
        VL_IN8(io_s0_fire_1,0,0);
        VL_IN8(io_s0_fire_2,0,0);
        VL_IN8(io_s0_fire_3,0,0);
        VL_IN8(io_s1_fire_0,0,0);
        VL_IN8(io_s1_fire_1,0,0);
    };
    struct {
        VL_IN8(io_s1_fire_2,0,0);
        VL_IN8(io_s1_fire_3,0,0);
        VL_IN8(io_s2_fire_0,0,0);
        VL_IN8(io_s2_fire_1,0,0);
        VL_IN8(io_s2_fire_2,0,0);
        VL_IN8(io_s2_fire_3,0,0);
        VL_IN8(io_s3_fire_2,0,0);
        VL_IN8(io_s3_redirect_2,0,0);
        VL_IN8(io_update_valid,0,0);
        VL_IN8(io_update_bits_ftb_entry_isCall,0,0);
        VL_IN8(io_update_bits_ftb_entry_isRet,0,0);
        VL_IN8(io_update_bits_ftb_entry_tailSlot_offset,3,0);
        VL_IN8(io_update_bits_ftb_entry_tailSlot_valid,0,0);
        VL_IN8(io_update_bits_cfi_idx_valid,0,0);
        VL_IN8(io_update_bits_cfi_idx_bits,3,0);
        VL_IN8(io_update_bits_jmp_taken,0,0);
        VL_IN8(io_redirect_valid,0,0);
        VL_IN8(io_redirect_bits_level,0,0);
        VL_IN8(io_redirect_bits_cfiUpdate_pd_isRVC,0,0);
        VL_IN8(io_redirect_bits_cfiUpdate_pd_isCall,0,0);
        VL_IN8(io_redirect_bits_cfiUpdate_pd_isRet,0,0);
        VL_IN8(io_redirect_bits_cfiUpdate_ssp,3,0);
        VL_IN8(io_redirect_bits_cfiUpdate_sctr,2,0);
        VL_IN8(io_redirect_bits_cfiUpdate_TOSW_flag,0,0);
        VL_IN8(io_redirect_bits_cfiUpdate_TOSW_value,4,0);
        VL_IN8(io_redirect_bits_cfiUpdate_TOSR_flag,0,0);
        VL_IN8(io_redirect_bits_cfiUpdate_TOSR_value,4,0);
        VL_IN8(io_redirect_bits_cfiUpdate_NOS_flag,0,0);
        VL_IN8(io_redirect_bits_cfiUpdate_NOS_value,4,0);
        CData/*0:0*/ RAS__DOT__clock;
        CData/*0:0*/ RAS__DOT__reset;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_offsets_0;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_offsets_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_offsets_0;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_offsets_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_offsets_0;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_offsets_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_is_jalr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_is_call;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_is_ret;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_last_may_be_rvi_call;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_offsets_0;
    };
    struct {
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_offsets_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_slot_valids_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_multiHit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_slot_valids_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_multiHit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_slot_valids_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_multiHit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_is_jalr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_is_call;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_is_ret;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_offsets_0;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_offsets_1;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_multiHit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_hit;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_isCall;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_isRet;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_isJalr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_valid;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_offset;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_valid;
        CData/*1:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_tarStat;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_offset;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_sharing;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_valid;
        CData/*1:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_tarStat;
        CData/*3:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_pftAddr;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_carry;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_last_may_be_rvi_call;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_always_taken_0;
        CData/*0:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_always_taken_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_0_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_0_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_0_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_0_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_0_offsets_0;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_0_offsets_1;
    };
    struct {
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_0_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_0_hit;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_1_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_1_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_1_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_1_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_1_offsets_0;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_1_offsets_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_1_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_1_hit;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_2_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_2_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_2_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_2_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_2_offsets_0;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_2_offsets_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_2_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_2_hit;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_3_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_3_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_3_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_3_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_3_offsets_0;
        CData/*3:0*/ RAS__DOT__io_out_s2_full_pred_3_offsets_1;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_3_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_3_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s2_full_pred_3_hit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_slot_valids_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_multiHit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_0_hit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_slot_valids_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_multiHit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_1_hit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_slot_valids_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_multiHit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_2_hit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_br_taken_mask_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_br_taken_mask_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_slot_valids_0;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_slot_valids_1;
        CData/*3:0*/ RAS__DOT__io_out_s3_full_pred_3_offsets_0;
        CData/*3:0*/ RAS__DOT__io_out_s3_full_pred_3_offsets_1;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_fallThroughErr;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_multiHit;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_is_br_sharing;
        CData/*0:0*/ RAS__DOT__io_out_s3_full_pred_3_hit;
        CData/*3:0*/ RAS__DOT__io_out_last_stage_spec_info_ssp;
        CData/*2:0*/ RAS__DOT__io_out_last_stage_spec_info_sctr;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_spec_info_TOSW_flag;
    };
    struct {
        CData/*4:0*/ RAS__DOT__io_out_last_stage_spec_info_TOSW_value;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_spec_info_TOSR_flag;
        CData/*4:0*/ RAS__DOT__io_out_last_stage_spec_info_TOSR_value;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_spec_info_NOS_flag;
        CData/*4:0*/ RAS__DOT__io_out_last_stage_spec_info_NOS_value;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_isCall;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_isRet;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_isJalr;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_valid;
        CData/*3:0*/ RAS__DOT__io_out_last_stage_ftb_entry_brSlots_0_offset;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_brSlots_0_sharing;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_brSlots_0_valid;
        CData/*1:0*/ RAS__DOT__io_out_last_stage_ftb_entry_brSlots_0_tarStat;
        CData/*3:0*/ RAS__DOT__io_out_last_stage_ftb_entry_tailSlot_offset;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_tailSlot_sharing;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_tailSlot_valid;
        CData/*1:0*/ RAS__DOT__io_out_last_stage_ftb_entry_tailSlot_tarStat;
        CData/*3:0*/ RAS__DOT__io_out_last_stage_ftb_entry_pftAddr;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_carry;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_last_may_be_rvi_call;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_always_taken_0;
        CData/*0:0*/ RAS__DOT__io_out_last_stage_ftb_entry_always_taken_1;
        CData/*0:0*/ RAS__DOT__io_ctrl_ras_enable;
        CData/*0:0*/ RAS__DOT__io_s0_fire_0;
        CData/*0:0*/ RAS__DOT__io_s0_fire_1;
        CData/*0:0*/ RAS__DOT__io_s0_fire_2;
        CData/*0:0*/ RAS__DOT__io_s0_fire_3;
        CData/*0:0*/ RAS__DOT__io_s1_fire_0;
        CData/*0:0*/ RAS__DOT__io_s1_fire_1;
        CData/*0:0*/ RAS__DOT__io_s1_fire_2;
        CData/*0:0*/ RAS__DOT__io_s1_fire_3;
        CData/*0:0*/ RAS__DOT__io_s2_fire_0;
        CData/*0:0*/ RAS__DOT__io_s2_fire_1;
        CData/*0:0*/ RAS__DOT__io_s2_fire_2;
        CData/*0:0*/ RAS__DOT__io_s2_fire_3;
        CData/*0:0*/ RAS__DOT__io_s3_fire_2;
        CData/*0:0*/ RAS__DOT__io_s3_redirect_2;
        CData/*0:0*/ RAS__DOT__io_update_valid;
        CData/*0:0*/ RAS__DOT__io_update_bits_ftb_entry_isCall;
        CData/*0:0*/ RAS__DOT__io_update_bits_ftb_entry_isRet;
        CData/*3:0*/ RAS__DOT__io_update_bits_ftb_entry_tailSlot_offset;
        CData/*0:0*/ RAS__DOT__io_update_bits_ftb_entry_tailSlot_valid;
        CData/*0:0*/ RAS__DOT__io_update_bits_cfi_idx_valid;
        CData/*3:0*/ RAS__DOT__io_update_bits_cfi_idx_bits;
        CData/*0:0*/ RAS__DOT__io_update_bits_jmp_taken;
        CData/*0:0*/ RAS__DOT__io_redirect_valid;
        CData/*0:0*/ RAS__DOT__io_redirect_bits_level;
        CData/*0:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_pd_isRVC;
        CData/*0:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_pd_isCall;
        CData/*0:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_pd_isRet;
        CData/*3:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_ssp;
        CData/*2:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_sctr;
        CData/*0:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_TOSW_flag;
        CData/*4:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_TOSW_value;
        CData/*0:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_TOSR_flag;
        CData/*4:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_TOSR_value;
        CData/*0:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_NOS_flag;
        CData/*4:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_NOS_value;
        CData/*3:0*/ RAS__DOT___RASStack_io_ssp;
        CData/*2:0*/ RAS__DOT___RASStack_io_sctr;
        CData/*0:0*/ RAS__DOT___RASStack_io_TOSR_flag;
        CData/*4:0*/ RAS__DOT___RASStack_io_TOSR_value;
        CData/*0:0*/ RAS__DOT___RASStack_io_TOSW_flag;
        CData/*4:0*/ RAS__DOT___RASStack_io_TOSW_value;
    };
    struct {
        CData/*0:0*/ RAS__DOT___RASStack_io_NOS_flag;
        CData/*4:0*/ RAS__DOT___RASStack_io_NOS_value;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_1_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_2_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_3_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_1_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_2_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_3_2;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_1;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_1_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_1_1;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_2_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_2_1;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_3_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s2_pc_modified_3_1;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_1;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_1_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_1_1;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_2_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_2_1;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_3_0;
        CData/*0:0*/ RAS__DOT__debug_modified_debug_s3_pc_modified_3_1;
        CData/*0:0*/ RAS__DOT__REG;
        CData/*0:0*/ RAS__DOT__REG_1;
        CData/*0:0*/ RAS__DOT___s2_spec_pop_T_8;
        CData/*0:0*/ RAS__DOT___s2_spec_pop_T_9;
        CData/*0:0*/ RAS__DOT__s2_spec_push;
        CData/*0:0*/ RAS__DOT__s2_spec_pop;
        CData/*0:0*/ RAS__DOT___GEN;
        CData/*0:0*/ RAS__DOT___GEN_0;
        CData/*0:0*/ RAS__DOT__s3_pushed_in_s2;
        CData/*0:0*/ RAS__DOT__s3_popped_in_s2;
        CData/*0:0*/ RAS__DOT___s3_pop_T_8;
        CData/*0:0*/ RAS__DOT___s3_pop_T_9;
        CData/*0:0*/ RAS__DOT__s3_push;
        CData/*0:0*/ RAS__DOT__s3_pop;
        CData/*3:0*/ RAS__DOT__s3_meta_ssp;
        CData/*2:0*/ RAS__DOT__s3_meta_sctr;
        CData/*0:0*/ RAS__DOT__s3_meta_TOSW_flag;
        CData/*4:0*/ RAS__DOT__s3_meta_TOSW_value;
        CData/*0:0*/ RAS__DOT__s3_meta_TOSR_flag;
        CData/*4:0*/ RAS__DOT__s3_meta_TOSR_value;
        CData/*0:0*/ RAS__DOT__s3_meta_NOS_flag;
        CData/*4:0*/ RAS__DOT__s3_meta_NOS_value;
        CData/*0:0*/ RAS__DOT__redirect_next_valid_last_REG;
        CData/*0:0*/ RAS__DOT__redirect_next_bits_r_level;
        CData/*0:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_pd_isRVC;
        CData/*0:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_pd_isCall;
        CData/*0:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_pd_isRet;
        CData/*3:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_ssp;
        CData/*2:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_sctr;
        CData/*0:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_TOSW_flag;
        CData/*4:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_TOSW_value;
        CData/*0:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_TOSR_flag;
        CData/*4:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_TOSR_value;
        CData/*0:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_NOS_flag;
        CData/*4:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_NOS_value;
        CData/*0:0*/ RAS__DOT___GEN_1;
        CData/*0:0*/ RAS__DOT____Vcellinp__RASStack__io_redirect_isRet;
        CData/*0:0*/ RAS__DOT____Vcellinp__RASStack__io_redirect_isCall;
    };
    struct {
        CData/*0:0*/ RAS__DOT____Vcellinp__RASStack__io_commit_pop_valid;
        CData/*0:0*/ RAS__DOT____Vcellinp__RASStack__io_commit_push_valid;
        CData/*0:0*/ RAS__DOT____Vcellinp__RASStack__io_s3_missed_push;
        CData/*0:0*/ RAS__DOT____Vcellinp__RASStack__io_s3_missed_pop;
        CData/*0:0*/ RAS__DOT____Vcellinp__RASStack__io_s3_cancel;
        CData/*0:0*/ RAS__DOT__reset_vector_pipMod__DOT__clock;
        CData/*0:0*/ RAS__DOT__reset_vector_pipMod__DOT__io_in_valid;
        CData/*0:0*/ RAS__DOT__reset_vector_pipMod__DOT__valid_REG;
        CData/*0:0*/ RAS__DOT__reset_vector_pipMod__DOT__valid_REG_1;
        CData/*0:0*/ RAS__DOT__reset_vector_pipMod__DOT__valid_REG_2;
        CData/*0:0*/ RAS__DOT__reset_vector_pipMod__DOT__valid_REG_3;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__clock;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__reset;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_spec_push_valid;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_spec_pop_valid;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s2_fire;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s3_fire;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s3_cancel;
        CData/*3:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_ssp;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_sctr;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_TOSW_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_TOSW_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_TOSR_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_TOSR_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_NOS_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_s3_meta_NOS_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s3_missed_pop;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_s3_missed_push;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_commit_push_valid;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_commit_pop_valid;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_commit_meta_TOSW_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_commit_meta_TOSW_value;
        CData/*3:0*/ RAS__DOT__RASStack__DOT__io_commit_meta_ssp;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_redirect_valid;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_redirect_isCall;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_redirect_isRet;
        CData/*3:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_ssp;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_sctr;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_TOSW_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_TOSW_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_TOSR_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_TOSR_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_NOS_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_redirect_meta_NOS_value;
        CData/*3:0*/ RAS__DOT__RASStack__DOT__io_ssp;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__io_sctr;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_TOSR_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_TOSR_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_TOSW_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_TOSW_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__io_NOS_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__io_NOS_value;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_0_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_1_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_2_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_3_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_4_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_5_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_6_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_7_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_8_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_9_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_10_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_11_ctr;
    };
    struct {
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_12_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_13_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_14_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__commit_stack_15_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_0_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_1_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_2_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_3_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_4_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_5_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_6_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_7_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_8_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_9_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_10_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_11_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_12_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_13_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_14_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_15_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_16_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_17_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_18_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_19_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_20_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_21_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_22_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_23_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_24_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_25_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_26_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_27_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_28_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_29_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_30_ctr;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__spec_queue_31_ctr;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_0_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_0_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_1_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_1_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_2_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_2_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_3_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_3_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_4_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_4_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_5_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_5_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_6_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_6_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_7_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_7_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_8_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_8_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_9_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_9_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_10_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_10_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_11_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_11_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_12_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_12_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_13_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_13_value;
    };
    struct {
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_14_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_14_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_15_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_15_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_16_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_16_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_17_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_17_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_18_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_18_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_19_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_19_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_20_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_20_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_21_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_21_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_22_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_22_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_23_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_23_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_24_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_24_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_25_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_25_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_26_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_26_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_27_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_27_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_28_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_28_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_29_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_29_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_30_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_30_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_nos_31_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__spec_nos_31_value;
        CData/*3:0*/ RAS__DOT__RASStack__DOT__nsp;
        CData/*3:0*/ RAS__DOT__RASStack__DOT__ssp;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__sctr;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__TOSR_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__TOSR_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__TOSW_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__TOSW_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__BOS_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__BOS_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__spec_overflowed;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__writeBypassEntry_ctr;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__writeBypassNos_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__writeBypassNos_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__writeBypassValid;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___realPush_T_4;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__topEntry_inflightValid;
        VlWide<3>/*95:0*/ RAS__DOT__RASStack__DOT___GEN_2;
        QData/*47:0*/ RAS__DOT__RASStack__DOT___GEN_5;
        VlWide<5>/*159:0*/ RAS__DOT__RASStack__DOT___GEN_7;
        CData/*4:0*/ RAS__DOT__RASStack__DOT___GEN_8;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__topNos_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__topNos_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__differentFlag_15;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__compare_15;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__differentFlag_16;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__compare_16;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__redirectTopEntry_inflightValid;
    };
    struct {
        CData/*0:0*/ RAS__DOT__RASStack__DOT___writeEntry_ctr_T_1;
        CData/*2:0*/ RAS__DOT__RASStack__DOT___sctr_T_12;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___writeEntry_ctr_T_7;
        CData/*2:0*/ RAS__DOT__RASStack__DOT___sctr_T;
        CData/*2:0*/ RAS__DOT__RASStack__DOT__realWriteEntry_next_ctr;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_9;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__realWriteAddr_next_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__realNos_next_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__realNos_next_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__realPush_r;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__realPush_REG;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__realPush;
        CData/*5:0*/ RAS__DOT__RASStack__DOT___GEN_10;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_11;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_12;
        CData/*3:0*/ RAS__DOT__RASStack__DOT___sctr_T_16;
        CData/*3:0*/ RAS__DOT__RASStack__DOT___sctr_T_8;
        CData/*5:0*/ RAS__DOT__RASStack__DOT___GEN_13;
        CData/*5:0*/ RAS__DOT__RASStack__DOT___GEN_14;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_15;
        CData/*3:0*/ RAS__DOT__RASStack__DOT___sctr_T_4;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__writeBypassValidWire;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__differentFlag_10;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__compare_10;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__differentFlag_11;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__compare_11;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__s3TopEntry_inflightValid;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_16;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_17;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_18;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_19;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_20;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_21;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___s3_missPushEntry_ctr_T;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___s3_missPushEntry_ctr_T_2;
        CData/*2:0*/ RAS__DOT__RASStack__DOT___sctr_T_10;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__realWriteAddr_value;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__realNos_flag;
        CData/*4:0*/ RAS__DOT__RASStack__DOT__realNos_value;
        CData/*5:0*/ RAS__DOT__RASStack__DOT___GEN_22;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_23;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_24;
        CData/*2:0*/ RAS__DOT__RASStack__DOT___GEN_25;
        CData/*2:0*/ RAS__DOT__RASStack__DOT___commit_stack_ctr_T;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_26;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_27;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_28;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_29;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_30;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_31;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_32;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_33;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_34;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_35;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_36;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_37;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_38;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_39;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_40;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_41;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_42;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_43;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_44;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_45;
    };
    struct {
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_46;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_47;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_48;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_49;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_50;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_51;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_52;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_53;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_54;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_55;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_56;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_57;
        CData/*3:0*/ RAS__DOT__RASStack__DOT___nsp_T_2;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_58;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_59;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_60;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_61;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_62;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_63;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_64;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_65;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_66;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_67;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_68;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_69;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_70;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_71;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_72;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_73;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_74;
        CData/*2:0*/ RAS__DOT__RASStack__DOT___commit_stack_ctr_T_2;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__inflightValid_8;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_75;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__inflightValid_6;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___GEN_76;
        CData/*0:0*/ RAS__DOT__RASStack__DOT__inflightValid_4;
        CData/*5:0*/ RAS__DOT__RASStack__DOT___BOS_new_ptr_T_11;
        CData/*5:0*/ RAS__DOT__RASStack__DOT___BOS_new_ptr_T_6;
        CData/*5:0*/ RAS__DOT__RASStack__DOT___BOS_new_ptr_T_1;
        CData/*2:0*/ RAS__DOT__RASStack__DOT___writeEntry_ctr_T_6;
        CData/*0:0*/ RAS__DOT__RASStack__DOT___writeEntry_ctr_T_9;
        CData/*4:0*/ __Vdly__RAS__DOT__RASStack__DOT__TOSR_value;
        CData/*0:0*/ __Vclklast__TOP__clock;
        CData/*0:0*/ __Vclklast__TOP__reset;
        VL_IN16(io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_lower,11,0);
        VL_OUT16(io_out_last_stage_ftb_entry_brSlots_0_lower,11,0);
        SData/*11:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_brSlots_0_lower;
        SData/*11:0*/ RAS__DOT__io_out_last_stage_ftb_entry_brSlots_0_lower;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_1_value;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_2_value;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_1_value_1;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_2_value_1;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_1_value_2;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_2_value_2;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_1_value_3;
        SData/*11:0*/ RAS__DOT__s2_pc_seg_2_value_3;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_1_value;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_2_value;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_1_value_1;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_2_value_1;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_1_value_2;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_2_value_2;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_1_value_3;
        SData/*11:0*/ RAS__DOT__s3_pc_seg_2_value_3;
    };
    struct {
        VL_IN(io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_lower,19,0);
        VL_OUTW(io_out_last_stage_meta,259,0,9);
        VL_OUT(io_out_last_stage_ftb_entry_tailSlot_lower,19,0);
        VL_INW(io_update_bits_meta,259,0,9);
        IData/*19:0*/ RAS__DOT__io_in_bits_resp_in_0_last_stage_ftb_entry_tailSlot_lower;
        VlWide<9>/*259:0*/ RAS__DOT__io_out_last_stage_meta;
        IData/*19:0*/ RAS__DOT__io_out_last_stage_ftb_entry_tailSlot_lower;
        VlWide<9>/*259:0*/ RAS__DOT__io_update_bits_meta;
        IData/*16:0*/ RAS__DOT__s2_pc_seg_0_value;
        IData/*16:0*/ RAS__DOT__s2_pc_seg_0_value_1;
        IData/*16:0*/ RAS__DOT__s2_pc_seg_0_value_2;
        IData/*16:0*/ RAS__DOT__s2_pc_seg_0_value_3;
        IData/*16:0*/ RAS__DOT__s3_pc_seg_0_value;
        IData/*16:0*/ RAS__DOT__s3_pc_seg_0_value_1;
        IData/*16:0*/ RAS__DOT__s3_pc_seg_0_value_2;
        IData/*16:0*/ RAS__DOT__s3_pc_seg_0_value_3;
        IData/*31:0*/ RAS__DOT__RASStack__DOT___GEN_6;
        VL_IN64(io_reset_vector,35,0);
        VL_IN64(io_in_bits_s0_pc_0,40,0);
        VL_IN64(io_in_bits_s0_pc_1,40,0);
        VL_IN64(io_in_bits_s0_pc_2,40,0);
        VL_IN64(io_in_bits_s0_pc_3,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_0_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_0_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_0_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_0_fallThroughAddr,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_1_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_1_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_1_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_1_fallThroughAddr,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_2_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_2_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_2_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_2_fallThroughAddr,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_3_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_3_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_3_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s2_full_pred_3_fallThroughAddr,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_0_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_0_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_0_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_0_fallThroughAddr,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_1_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_1_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_1_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_1_fallThroughAddr,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_2_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_2_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_2_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_2_fallThroughAddr,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_3_targets_0,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_3_targets_1,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_3_jalr_target,40,0);
        VL_IN64(io_in_bits_resp_in_0_s3_full_pred_3_fallThroughAddr,40,0);
        VL_OUT64(io_out_s2_pc_0,40,0);
        VL_OUT64(io_out_s2_pc_1,40,0);
        VL_OUT64(io_out_s2_pc_2,40,0);
        VL_OUT64(io_out_s2_pc_3,40,0);
        VL_OUT64(io_out_s2_full_pred_0_targets_0,40,0);
        VL_OUT64(io_out_s2_full_pred_0_targets_1,40,0);
        VL_OUT64(io_out_s2_full_pred_0_fallThroughAddr,40,0);
        VL_OUT64(io_out_s2_full_pred_1_targets_0,40,0);
        VL_OUT64(io_out_s2_full_pred_1_targets_1,40,0);
        VL_OUT64(io_out_s2_full_pred_1_fallThroughAddr,40,0);
    };
    struct {
        VL_OUT64(io_out_s2_full_pred_2_targets_0,40,0);
        VL_OUT64(io_out_s2_full_pred_2_targets_1,40,0);
        VL_OUT64(io_out_s2_full_pred_2_fallThroughAddr,40,0);
        VL_OUT64(io_out_s2_full_pred_3_targets_0,40,0);
        VL_OUT64(io_out_s2_full_pred_3_targets_1,40,0);
        VL_OUT64(io_out_s2_full_pred_3_fallThroughAddr,40,0);
        VL_OUT64(io_out_s3_pc_0,40,0);
        VL_OUT64(io_out_s3_pc_1,40,0);
        VL_OUT64(io_out_s3_pc_2,40,0);
        VL_OUT64(io_out_s3_pc_3,40,0);
        VL_OUT64(io_out_s3_full_pred_0_targets_0,40,0);
        VL_OUT64(io_out_s3_full_pred_0_targets_1,40,0);
        VL_OUT64(io_out_s3_full_pred_0_fallThroughAddr,40,0);
        VL_OUT64(io_out_s3_full_pred_1_targets_0,40,0);
        VL_OUT64(io_out_s3_full_pred_1_targets_1,40,0);
        VL_OUT64(io_out_s3_full_pred_1_fallThroughAddr,40,0);
        VL_OUT64(io_out_s3_full_pred_2_targets_0,40,0);
        VL_OUT64(io_out_s3_full_pred_2_targets_1,40,0);
        VL_OUT64(io_out_s3_full_pred_2_fallThroughAddr,40,0);
        VL_OUT64(io_out_s3_full_pred_3_targets_0,40,0);
        VL_OUT64(io_out_s3_full_pred_3_targets_1,40,0);
        VL_OUT64(io_out_s3_full_pred_3_fallThroughAddr,40,0);
        VL_OUT64(io_out_last_stage_spec_info_topAddr,40,0);
        VL_IN64(io_redirect_bits_cfiUpdate_pc,40,0);
        QData/*35:0*/ RAS__DOT__io_reset_vector;
        QData/*40:0*/ RAS__DOT__io_in_bits_s0_pc_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_s0_pc_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_s0_pc_2;
        QData/*40:0*/ RAS__DOT__io_in_bits_s0_pc_3;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_0_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_1_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_2_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s2_full_pred_3_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_0_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_1_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_2_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_targets_0;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_targets_1;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_jalr_target;
        QData/*40:0*/ RAS__DOT__io_in_bits_resp_in_0_s3_full_pred_3_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s2_pc_0;
        QData/*40:0*/ RAS__DOT__io_out_s2_pc_1;
        QData/*40:0*/ RAS__DOT__io_out_s2_pc_2;
    };
    struct {
        QData/*40:0*/ RAS__DOT__io_out_s2_pc_3;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_0_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_0_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_0_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_1_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_1_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_1_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_2_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_2_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_2_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_3_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_3_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s2_full_pred_3_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s3_pc_0;
        QData/*40:0*/ RAS__DOT__io_out_s3_pc_1;
        QData/*40:0*/ RAS__DOT__io_out_s3_pc_2;
        QData/*40:0*/ RAS__DOT__io_out_s3_pc_3;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_0_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_0_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_0_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_1_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_1_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_1_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_2_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_2_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_2_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_3_targets_0;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_3_targets_1;
        QData/*40:0*/ RAS__DOT__io_out_s3_full_pred_3_fallThroughAddr;
        QData/*40:0*/ RAS__DOT__io_out_last_stage_spec_info_topAddr;
        QData/*40:0*/ RAS__DOT__io_redirect_bits_cfiUpdate_pc;
        QData/*40:0*/ RAS__DOT___RASStack_io_spec_pop_addr;
        QData/*35:0*/ RAS__DOT___reset_vector_pipMod_io_out_bits;
        QData/*40:0*/ RAS__DOT__s1_pc_dup_0;
        QData/*40:0*/ RAS__DOT__s1_pc_dup_1;
        QData/*40:0*/ RAS__DOT__s1_pc_dup_2;
        QData/*40:0*/ RAS__DOT__s1_pc_dup_3;
        QData/*40:0*/ RAS__DOT__debug_s2_pc_addr;
        QData/*40:0*/ RAS__DOT__debug_s2_pc_addr_1;
        QData/*40:0*/ RAS__DOT__debug_s2_pc_addr_2;
        QData/*40:0*/ RAS__DOT__debug_s2_pc_addr_3;
        QData/*40:0*/ RAS__DOT__debug_s3_pc_addr;
        QData/*40:0*/ RAS__DOT__debug_s3_pc_addr_1;
        QData/*40:0*/ RAS__DOT__debug_s3_pc_addr_2;
        QData/*40:0*/ RAS__DOT__debug_s3_pc_addr_3;
        QData/*40:0*/ RAS__DOT___s2_spec_new_addr_T_1;
        QData/*40:0*/ RAS__DOT__s3_top;
        QData/*40:0*/ RAS__DOT__s3_spec_new_addr;
        QData/*40:0*/ RAS__DOT__redirect_next_bits_r_cfiUpdate_pc;
        QData/*40:0*/ RAS__DOT___GEN_2;
        QData/*40:0*/ RAS__DOT____Vcellinp__RASStack__io_redirect_callAddr;
        QData/*35:0*/ RAS__DOT__reset_vector_pipMod__DOT__io_in_bits;
        QData/*35:0*/ RAS__DOT__reset_vector_pipMod__DOT__io_out_bits;
        QData/*35:0*/ RAS__DOT__reset_vector_pipMod__DOT__data;
        QData/*35:0*/ RAS__DOT__reset_vector_pipMod__DOT__data_1;
        QData/*35:0*/ RAS__DOT__reset_vector_pipMod__DOT__data_2;
        QData/*35:0*/ RAS__DOT__reset_vector_pipMod__DOT__data_3;
        QData/*35:0*/ RAS__DOT__reset_vector_pipMod__DOT__res_bits;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__io_spec_push_addr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__io_s3_pushAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__io_spec_pop_addr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__io_redirect_callAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_0_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_1_retAddr;
    };
    struct {
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_2_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_3_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_4_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_5_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_6_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_7_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_8_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_9_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_10_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_11_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_12_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_13_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_14_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__commit_stack_15_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_0_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_1_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_2_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_3_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_4_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_5_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_6_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_7_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_8_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_9_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_10_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_11_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_12_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_13_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_14_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_15_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_16_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_17_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_18_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_19_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_20_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_21_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_22_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_23_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_24_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_25_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_26_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_27_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_28_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_29_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_30_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__spec_queue_31_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__writeBypassEntry_retAddr;
        VlWide<41>/*1311:0*/ RAS__DOT__RASStack__DOT___GEN_0;
        QData/*40:0*/ RAS__DOT__RASStack__DOT___GEN_1;
        VlWide<21>/*655:0*/ RAS__DOT__RASStack__DOT___GEN_3;
        QData/*40:0*/ RAS__DOT__RASStack__DOT___GEN_4;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__writeEntry_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__timingTop_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__realWriteEntry_next_retAddr;
        QData/*40:0*/ RAS__DOT__RASStack__DOT__realWriteEntry_retAddr;
        VlUnpacked<IData/*31:0*/, 22> RAS__DOT___RANDOM;
        VlUnpacked<IData/*31:0*/, 6> RAS__DOT__reset_vector_pipMod__DOT___RANDOM;
        VlUnpacked<IData/*31:0*/, 78> RAS__DOT__RASStack__DOT___RANDOM;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;  // Symbol table

    // CONSTRUCTORS
    Vtop___024root(const char* name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(Vtop__Syms* symsp, bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
